ALTER TABLE seminar_halls
  ADD COLUMN open_time TIME NOT NULL DEFAULT '08:00:00',
  ADD COLUMN close_time TIME NOT NULL DEFAULT '20:00:00';ALTER TABLE seminar_halls
  ADD COLUMN open_time TIME NOT NULL DEFAULT '08:00:00',
  ADD COLUMN close_time TIME NOT NULL DEFAULT '20:00:00';